### ISSUE TITLE
Homepage feels squished, need to make the content blocks taller

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#2]
<img width="1428" alt="screen shot 2016-01-25 at 12 35 39 am" src="https://cloud.githubusercontent.com/assets/16873520/12543624/35c7fa2c-c2ff-11e5-8575-1c7bb87d42fe.png">

The big light yellow block on the homepage is too short. It should almost fill the whole browser window when you come to the site. Then that will allow more room for the headline type to get bigger, and spread out more on the page. Button will also move down, as marked in pink, and the top nav moves down from the top of the browser window.

This is a screenshot of the Illustrator file - so you can see how much more spread out everything is compared to the developed site:

<img width="1041" alt="screen shot 2016-01-25 at 12 36 05 am" src="https://cloud.githubusercontent.com/assets/16873520/12543641/63c2bb24-c2ff-11e5-9525-417f0a9985f3.png">

**Comment by nisho5** [comment]
- done

**Comment by laurakberglund** [comment]
<img width="1438" alt="screen shot 2016-01-25 at 10 27 11 pm" src="https://cloud.githubusercontent.com/assets/16873520/12571802/d5d414d4-c3b2-11e5-9eac-263ef8bf501b.png">

This page still does not look right, we need to be trying to match the way it looks in the .ai file exactly. See how you uncreased the leading (space between lines of text) rather than just making the headline text bigger overall?

Also, it looks like the nav text got bigger, but now it is running into two lines, which we never want to have happen.

**Comment by nisho5** [comment]
I decressed the spacing to half what it was and increasted the font size.

Also, i fixed the menu. It should not collapse anymore.
