### ISSUE TITLE
Main button style

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#3]
<img width="223" alt="screen shot 2016-01-25 at 1 05 24 am" src="https://cloud.githubusercontent.com/assets/16873520/12543677/cf3fe020-c2ff-11e5-870d-4c9c448e1df2.png">
<img width="370" alt="screen shot 2016-01-25 at 1 05 35 am" src="https://cloud.githubusercontent.com/assets/16873520/12543678/cf58aa2e-c2ff-11e5-90a9-66e67b741d7a.png">

See differences in the button styles in screenshots.
- Type needs much more letterspacing
- Type for "GET STARTED" is Calibre Semibold, not bold
- Box line weight is a little bit thicker
- Box needs to get wider
- Placed too close to the bottom of the yellow content block, needs more breathing room around it.

**Comment by nisho5** [comment]
- Done

**Comment by laurakberglund** [comment]
<img width="758" alt="screen shot 2016-01-25 at 10 31 28 pm" src="https://cloud.githubusercontent.com/assets/16873520/12571858/68f8a298-c3b3-11e5-81c1-7cdda8191f31.png">

This is closer, but still not completely right. See screenshot above, yours is on the right, and the original design is on the left.
- Tracking on "Get Started" needs to be increased slightly more
- Tracking on "Or sign in" needs to be increased.
- The "sign in" part of the text looks too light, it should be one weight heavier
- width of box needs to get a bit longer

**Comment by nisho5** [comment]
Done.
Please check

**Comment by laurakberglund** [comment]
This is so close! The only thing that needs to still be fixed is the "OR" - it needs to match the letter spacing on the other words. It still looks too tight right now.

**Comment by nisho5** [comment]
Done

**Comment by laurakberglund** [comment]
looks good!
